#!/bin/bash

err=0
trap 'err=1' ERR

adduser runner
sudo -u runner mkdir -p /home/runner/.ssh
sudo -u runner touch /home/runner/.ssh/authorized_keys
sudo -u runner chmod 640 /home/runner/.ssh/authorized_keys
sudo -u runner chmod 700 /home/runner/.ssh
cat private/id_rsa.pub >> /home/runner/.ssh/authorized_keys
chattr +i  ~runner

exit "$err"
