#!/bin/bash

err=0
trap 'err=1' ERR

semanage fcontext -a -t bin_t '/srv/bin(/.*)?'
semanage fcontext -a -t bin_t '/srv/wrappers(/.*)?'
restorecon -Rv /home/runner/.ssh/authorized_keys
restorecon -Rv /srv/bin
restorecon -Rv /srv/wrappers

semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/swipl-.*/bin/x86_64-linux(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/node_modules/coffee-script/bin(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/golang/bin(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/node_modules/babel-cli/bin(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/pypy-.*/bin(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib/node_modules/cheddar-lang/dist/cli(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/clisp-.*/base(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/maxima/.*/binary-sbcl(/.*)?'
semanage fcontext -a -s system_u -t bin_t '/usr/lib/golang/pkg/tool/linux_amd64(/.*)?'
restorecon -Rv /usr/lib /usr/lib64

exit "$err"
