#!/bin/bash

err=0
trap 'err=1' ERR

semanage fcontext -a -t bin_t '/srv/bin(/.*)?'
semanage fcontext -a -t bin_t '/srv/wrappers(/.*)?'
restorecon -Rv /home/runner/.ssh/authorized_keys
restorecon -Rv /srv/bin
restorecon -Rv /srv/wrappers

semanage fcontext -a -s system_u -t bin_t '/usr/lib(64)?/.*/bin(/.*)?'
restorecon -Rv /usr/lib /usr/lib64

exit "$err"
