#!/bin/bash

err=0
trap 'err=1' ERR

dnf install allegro5-devel allegro5-addon-ttf-devel allegro5-addon-image-devel allegro5-addon-audio-devel allegro5-addon-acodec-devel \
  ant bison bison-devel chicken clang clisp clojure cmake dash emacs-nox erlang-erts fish flex flex-devel fsharp gc-devel gcc-c++ \
  gforth glib2-devel glibc-devel glibc-devel.i686 golang groovy gtkglext-libs haskell-platform icu java-1.?.0-openjdk java-9-openjdk-devel\
  julia ksh libgcc.i686 lldb lldb-devel lttng-tools lttng-ust maxima mercurial mono-basic mono-complete nasm ncurses-compat-libs \
  neovim nim npm ocaml octave octave-devel patch pcre-devel perl-Digest-CRC perl-List-MoreUtils perl-Text-Soundex php-cli pl \
  pyephem pypy python-devel python3-devel R-littler rakudo ruby rubygem-treetop rust tcsh time vala vim-common wget zsh -y

dnf install \
  apache-commons-beanutils-1.9.2-5.fc24.noarch \
  apache-commons-beanutils-javadoc-1.9.2-5.fc24.noarch \
  apache-commons-chain-1.2-13.fc24.noarch \
  apache-commons-chain-javadoc-1.2-13.fc24.noarch \
  apache-commons-cli-javadoc-1.3.1-3.fc24.noarch \
  apache-commons-codec-1.10-3.fc24.noarch \
  apache-commons-codec-javadoc-1.10-3.fc24.noarch \
  apache-commons-collections-3.2.2-3.fc24.noarch \
  apache-commons-collections4-4.0-6.fc24.noarch \
  apache-commons-collections4-javadoc-4.0-6.fc24.noarch \
  apache-commons-collections-javadoc-3.2.2-3.fc24.noarch \
  apache-commons-collections-testframework-3.2.2-3.fc24.noarch \
  apache-commons-compress-1.10-0.3.svn1684406.fc24.1.noarch \
  apache-commons-compress-javadoc-1.10-0.3.svn1684406.fc24.1.noarch \
  apache-commons-configuration-1.10-6.fc24.noarch \
  apache-commons-configuration-javadoc-1.10-6.fc24.noarch \
  apache-commons-csv-1.2-1.fc24.noarch \
  apache-commons-csv-javadoc-1.2-1.fc24.noarch \
  apache-commons-daemon-1.0.15-11.fc24.x86_64 \
  apache-commons-daemon-javadoc-1.0.15-11.fc24.noarch \
  apache-commons-daemon-jsvc-1.0.15-11.fc24.x86_64 \
  apache-commons-dbcp-1.4-20.fc24.noarch \
  apache-commons-dbcp-javadoc-1.4-20.fc24.noarch \
  apache-commons-dbutils-1.5-10.fc24.noarch \
  apache-commons-dbutils-javadoc-1.5-10.fc24.noarch \
  apache-commons-digester-2.1-6.fc24.noarch \
  apache-commons-digester-javadoc-2.1-6.fc24.noarch \
  apache-commons-discovery-2:0.5-15.fc24.noarch \
  apache-commons-discovery-javadoc-2:0.5-15.fc24.noarch \
  apache-commons-el-1.0-36.fc24.noarch \
  apache-commons-el-javadoc-1.0-36.fc24.noarch \
  apache-commons-email-1.3.1-5.fc24.noarch \
  apache-commons-email-javadoc-1.3.1-5.fc24.noarch \
  apache-commons-exec-1.3-4.fc24.noarch \
  apache-commons-exec-javadoc-1.3-4.fc24.noarch \
  apache-commons-fileupload-1.3.1-8.fc24.noarch \
  apache-commons-fileupload-javadoc-1.3.1-8.fc24.noarch \
  apache-commons-io-1:2.4-15.fc24.noarch \
  apache-commons-io-javadoc-1:2.4-15.fc24.noarch \
  apache-commons-javaflow-1.0-0.11.20120509SNAPSHOT.fc24.noarch \
  apache-commons-javaflow-ant-1.0-0.11.20120509SNAPSHOT.fc24.noarch \
  apache-commons-javaflow-javadoc-1.0-0.11.20120509SNAPSHOT.fc24.noarch \
  apache-commons-jci-1.1-3.fc24.noarch \
  apache-commons-jci-core-1.1-3.fc24.noarch \
  apache-commons-jci-eclipse-1.1-3.fc24.noarch \
  apache-commons-jci-fam-1.1-3.fc24.noarch \
  apache-commons-jci-groovy-1.1-3.fc24.noarch \
  apache-commons-jci-janino-1.1-3.fc24.noarch \
  apache-commons-jci-javadoc-1.1-3.fc24.noarch \
  apache-commons-jci-rhino-1.1-3.fc24.noarch \
  apache-commons-jcs-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jcs-core-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jcs-javadoc-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jcs-jcache-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jcs-jcache-extras-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jcs-jcache-openjpa-2.0-0.3.beta.1.fc24.noarch \
  apache-commons-jexl-2.1.1-15.fc24.noarch \
  apache-commons-jexl-javadoc-2.1.1-15.fc24.noarch \
  apache-commons-jxpath-1.3-25.fc24.noarch \
  apache-commons-jxpath-javadoc-1.3-25.fc24.noarch \
  apache-commons-lang-2.6-18.fc24.noarch \
  apache-commons-lang3-3.4-4.fc24.noarch \
  apache-commons-lang3-javadoc-3.4-4.fc24.noarch \
  apache-commons-lang-javadoc-2.6-18.fc24.noarch \
  apache-commons-launcher-1.1-18.20100521svn936225.fc24.noarch \
  apache-commons-launcher-javadoc-1.1-18.20100521svn936225.fc24.noarch \
  apache-commons-logging-javadoc-1.2-5.fc24.noarch \
  apache-commons-math-3.4.1-3.fc24.noarch \
  apache-commons-math-javadoc-3.4.1-3.fc24.noarch \
  apache-commons-modeler-2.0.1-17.fc24.noarch \
  apache-commons-modeler-javadoc-2.0.1-17.fc24.noarch \
  apache-commons-net-3.4-3.fc24.noarch \
  apache-commons-net-javadoc-3.4-3.fc24.noarch \
  apache-commons-ognl-3.0.2-11.20120313svn1102435.fc24.noarch \
  apache-commons-ognl-javadoc-3.0.2-11.20120313svn1102435.fc24.noarch \
  apache-commons-parent-39-2.fc24.noarch \
  apache-commons-pool-1.6-12.fc24.noarch \
  apache-commons-pool2-2.4.2-2.fc24.noarch \
  apache-commons-pool2-javadoc-2.4.2-2.fc24.noarch \
  apache-commons-pool-javadoc-1.6-12.fc24.noarch \
  apache-commons-primitives-1.1-0.3.678495.fc24.noarch \
  apache-commons-primitives-javadoc-1.1-0.3.678495.fc24.noarch \
  apache-commons-validator-1.5.0-2.fc24.noarch \
  apache-commons-validator-javadoc-1.5.0-2.fc24.noarch \
  apache-commons-vfs-2.0-17.fc24.noarch \
  apache-commons-vfs-ant-2.0-17.fc24.noarch \
  apache-commons-vfs-examples-2.0-17.fc24.noarch \
  apache-commons-vfs-javadoc-2.0-17.fc24.noarch -y

exit "$err"
