#!/bin/bash

err=0
trap 'err=1' ERR

mkdir -p tmp
cd tmp
wget http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/19/Everything/x86_64/os/Packages/l/libicu-50.1.2-5.fc19.x86_64.rpm
wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.15/powershell-6.0.0_alpha.15-1.el7.centos.x86_64.rpm
rpm2cpio libicu-50.1.2-5.fc19.x86_64.rpm | cpio -idmv
dnf install powershell-6.0.0_alpha.15-1.el7.centos.x86_64.rpm -y
rm -f powershell-6.0.0_alpha.15-1.el7.centos.x86_64.rpm
rm -f libicu-50.1.2-5.fc19.x86_64.rpm
mkdir -p /opt/microsoft/lib/
cp usr/lib64/* /opt/microsoft/lib/
cp ../files/aliases.ps1 /opt/microsoft/lib/
rm -rf usr
cd ..
rm -rf tmp

exit "$err"
