#!/bin/bash

err=0
trap 'err=1' ERR

git clone https://github.com/TryItOnline/arena-server.git
if [[ ! -z $ArenaServerCommit ]]; then
    cd arena-server
    git checkout $ArenaServerCommit
    cd ..
fi
yes | cp -r ./arena-server/* /srv
rm -rf ./arena-server

exit "$err"
