#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf /srv
git clone https://github.com/TryItOnline/arena-server.git /srv
source private/config

if [[ ! -z $ArenaServerCommit ]]; then
    git -C /srv checkout $ArenaServerCommit
fi

exit "$err"
