#!/bin/bash

err=0
trap 'err=1' ERR

dnf install allegro5-devel ant bison bison-devel bsd-games ceylon-1.3.2 chicken clang clisp -y

dnf install clojure cmake dash emacs-nox erlang-erts fish flex flex-devel  -y

dnf install fsharp gc-devel gcc-c++ gforth glib2-devel glibc-devel glibc-devel.i686 gradle -y

dnf install golang  -y

dnf install gmp-c++ gmp-devel ImageMagick libX11-devel -y

dnf install groovy gtkglext-libs icu java-1.?.0-openjdk java-9-openjdk-devel jq ksh -y

dnf install libgcc.i686 lldb lldb-devel lttng-tools lttng-ust maxima mercurial mono-basic mono-complete nasm -y

dnf install ncurses-compat-libs neovim npm ocaml octave octave-devel outils patch pcre-devel perl-Digest-CRC \
  perl-List-MoreUtils perl-Text-Soundex php-cli pl pyephem pypy python-devel python3-devel R-littler rakudo \
  ruby rust tcsh time tree vala vim-common wget words zsh -y

dnf install 'apache-commons-*' -y

exit "$err"
