#!/bin/bash

err=0
trap 'err=1' ERR

wget http://downloads.dlang.org/releases/2.x/2.073.0/dmd-2.073.0-0.fedora.x86_64.rpm
sync && echo 3 > /proc/sys/vm/drop_caches
dnf install dmd-2.073.0-0.fedora.x86_64.rpm -y
rm -f dmd-2.073.0-0.fedora.x86_64.rpm

exit "$err"
