#!/bin/bash

err=0
trap 'err=1' ERR

saveddir=$(pwd)

mkdir -p tmp
cd tmp
rm -f /usr/local/bin/dotnet
rm -rf /opt/microsoft/home
mkdir -p /opt/microsoft/dotnet
ln -s /opt/microsoft/ usr
rpm2cpio https://dl.fedoraproject.org/pub/fedora/linux/releases/24/Server/x86_64/os/Packages/l/libicu-56.1-4.fc24.x86_64.rpm | cpio -dim 
rpm2cpio https://dl.fedoraproject.org/pub/fedora/linux/releases/25/Everything/x86_64/os/Packages/l/lldb-3.8.0-2.fc25.x86_64.rpm | cpio -dim
curl -sSL https://go.microsoft.com/fwlink/?LinkID=835025 | tar xz -C /opt/microsoft/dotnet
ln -s /opt/microsoft/dotnet/dotnet /usr/local/bin
mkdir -p /opt/microsoft/home
pushd /opt/microsoft/home
mkdir -p /root/waldo
cp "$saveddir/files/project.json" ./project.json
LD_LIBRARY_PATH=/opt/microsoft/lib64 TMPDIR=/root/waldo HOME=/opt/netcore dotnet restore
rm -rf /root/waldo
popd
cd ..
rm -rf tmp 

exit "$err"
