#!/bin/bash

err=0
trap 'err=1' ERR

wget http://sourceforge.net/projects/regina-rexx/files/regina-rexx/3.9.1/Regina-REXX-3.9.1-1.x86_64-CentOS-6.5.rpm
wget http://sourceforge.net/projects/regina-rexx/files/regina-rexx/3.9.1/Regina-REXX-lib-3.9.1-1.x86_64-CentOS-6.5.rpm
dnf install ./Regina-REXX-lib-3.9.1-1.x86_64-CentOS-6.5.rpm
dnf install ./Regina-REXX-3.9.1-1.x86_64-CentOS-6.5.rpm -y

rm -f ./Regina-REXX-lib-3.9.1-1.x86_64-CentOS-6.5.rpm
rm -f ./Regina-REXX-3.9.1-1.x86_64-CentOS-6.5.rpm

exit "$err"
