#!/bin/bash

err=0
trap 'err=1' ERR

pushd /opt
for dyalogzip in linux_64_*_unicode.zip; do
        dyalogrpm=${dyalogzip%.zip}.x86_64.rpm
done

rm -f $dyalogrpm

if unzip $dyalogzip $dyalogrpm; then
        dnf install -y $dyalogrpm
        rm -f linux_64_*_unicode.zip $dyalogrpm
else
        err=1
fi
popd

exit "$err"
