#!/bin/bash

err=0
trap 'err=1' ERR

#this particular version of jdk does not link the cers,  roda fail to build as the result
ln -s ../../../../../../../etc/pki/java/cacerts /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-10.b14.fc25.x86_64/jre/lib/security/cacerts

# just for good measure (battling OOM reaper)
sync && echo 3 > /proc/sys/vm/drop_caches

exit "$err"
