#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf grime
git clone https://github.com/iatorm/grime.git
cd grime
echo '"Hello, World!"' > code
echo '"Hello, World!"' > input
HOME=/root ./rungrime code input
rm -f code
rm -f input
cd ..

exit "$err"
