#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf racket
wget https://mirror.racket-lang.org/installers/6.8/racket-6.8-x86_64-linux.sh
sh ./racket-6.8-x86_64-linux.sh --dest racket --in-place
rm -f racket-6.8-x86_64-linux.sh

exit "$err"
