#!/usr/bin/env bash

saveddir=/opt/tiosetup

mkdir -p /opt/microsoft/tmp

mkdir -p /opt/microsoft/home/csharp
mkdir -p /opt/microsoft/home/fsharp
mkdir -p /opt/microsoft/home/vb
cd /opt/microsoft/home/csharp
cp "$saveddir/files/dotnet/project.csproj" ./project.csproj
cp "$saveddir/files/dotnet/code.cs" ./code.cs
cp "$saveddir/files/dotnet/opts.txt" ./opts.txt
HOME=/opt/microsoft/home TMPDIR=/opt/microsoft/tmp dotnet build
rm -rf /opt/microsoft/home/csharp/obj/Debug
rm -f /opt/microsoft/home/csharp/bin/Debug/netcoreapp*/project.dll
rm -f /opt/microsoft/home/csharp/bin/Debug/netcoreapp*/project.pdb
rm -f /opt/microsoft/home/csharp/bin/Debug/netcoreapp*/project.deps.json

cd /opt/microsoft/home/vb
cp "$saveddir/files/dotnet/project.vbproj" ./project.vbproj
HOME=/opt/microsoft/home TMPDIR=/opt/microsoft/tmp dotnet restore

cd /opt/microsoft/home/fsharp
cp "$saveddir/files/dotnet/project.fsproj" ./project.fsproj
HOME=/opt/microsoft/home TMPDIR=/opt/microsoft/tmp dotnet restore

rm -rf /opt/microsoft/tmp

touch --date='+100 years' /opt/microsoft/home/.local/share/NuGet/v3-cache/*/{list_FSharp.Core,service_index}.dat
