#!/bin/bash 

dnf install lldb-devel lttng-ust -y
rm -rf /opt/microsoft
rm -f /usr/local/bin/dotnet
mkdir -p /opt/microsoft/dotnet
rpm2cpio https://dl.fedoraproject.org/pub/fedora/linux/releases/24/Server/x86_64/os/Packages/l/libicu-56.1-4.fc24.x86_64.rpm | cpio -dim -D /
rpm2cpio https://dl.fedoraproject.org/pub/fedora/linux/releases/25/Everything/x86_64/os/Packages/l/lldb-3.8.0-2.fc25.x86_64.rpm | cpio -dim -D /
curl -sSL https://go.microsoft.com/fwlink/?LinkID=843461 | tar xz -C /opt/microsoft/dotnet
#find /opt/microsoft/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
ln -s /opt/microsoft/dotnet/dotnet /usr/local/bin
cd /opt/TioTests
mkdir -p /root/tmp
TMPDIR=/root/tmp HOME=/root dotnet restore
HOME=/root dotnet build
rm -rf /root/tmp
