#!/bin/bash

usage()
{
	printf "$0: Usage: tiopull [-n] {-a | LANGUAGE...}\n" >&2
	exit 1
}

set -- $(getopt an "$@")

while true; do
	case "$1" in
		-a) shift; all=1;;
		-n) shift; nodryrun=1;;
		--) shift; break;;
		 *) usage;;
	esac
done

cd /opt
echo -n 'Updating tiosetup... '
git -C tiosetup pull

if ((all)); then
	tiosetup/run-scripts tiosetup/languages
elif (($#)); then
	for language in "$@"; do
		printf "\nInstalling/updating $language.\n"
		tiosetup/languages/$language
	done
	set -- -v -l "$@"
else
	usage
fi

((nodryrun)) || tiodryrun "$@"
