#!/bin/bash

if (($# == 0)); then
	printf "$0: missing parameter\nUsage: tiopull {-a | LANGUAGE...}\n"
	exit 1
fi

cd /opt
echo -n 'Updating tiosetup... '
git -C tiosetup pull

if [[ "$*" == -a ]]; then
	tiosetup/run-scripts tiosetup/languages
else
	for language in $*; do
		printf "\nInstalling/updating $language.\n"
		tiosetup/languages/$language
	done
fi
