#!/bin/bash 

cd /opt

if [[ "$1" == -a ]]; then
  /opt/TioSetup/run-scripts /opt/TioSetup/languages
else
  if [[ "$1 ]]; then
    /opt/TioSetup/languages/$1
  else
    echo "Missing parameter. Usage: tiopull language|-a"
  fi
fi
