#!/bin/bash

err=0
trap 'err=1' ERR

source private/setup.conf 

if [[ ! -z $SwapfileSize ]]; then
    dd if=/dev/zero of=/swapfile bs=1024 count="$SwapfileSize"
    chmod 0600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
fi

exit "$err"
