#!/bin/bash

err=0
trap 'err=1' ERR

mkdir -p tmp
cd tmp
cp ../files/sandbox_extra.te .
make -f /usr/share/selinux/devel/Makefile sandbox_extra.pp
semodule -i sandbox_extra.pp
cd ..
rm -rf tmp

exit "$err"
