#!/bin/bash

err=0
trap 'err=1' ERR

cp files/sandbox_extra.te ./sandbox_extra.te
make -f /usr/share/selinux/devel/Makefile sandbox_extra.pp
semodule -i sandbox_extra.pp
rm -f sandbox_extra.*

exit "$err"
