#!/bin/bash

err=0
trap 'err=1' ERR

mkdir -p tmp
cd tmp
wget https://haskell.org/platform/download/8.0.2/haskell-platform-8.0.2-unknown-posix--full-x86_64.tar.gz
tar zxvf haskell-platform-8.0.2-unknown-posix--full-x86_64.tar.gz
rm -f haskell-platform-8.0.2-unknown-posix--full-x86_64.tar.gz
./install-haskell-platform.sh
cd ..
rm -rf tmp

exit "$err"
