Set-Alias ac Add-Content -Option AllScope -Scope Global
Set-Alias cat Get-Content -Option AllScope -Scope Global
Set-Alias cp Copy-Item -Option AllScope -Scope Global
Set-Alias cpp Copy-ItemProperty -Option AllScope -Scope Global
Set-Alias diff Compare-Object -Option AllScope -Scope Global
Set-Alias ls Get-ChildItem -Option AllScope -Scope Global
Set-Alias man help -Option AllScope -Scope Global
Set-Alias mount New-PSDrive -Option AllScope -Scope Global
Set-Alias mv Move-Item -Option AllScope -Scope Global
Set-Alias ps Get-Process -Option AllScope -Scope Global
Set-Alias rm Remove-Item -Option AllScope -Scope Global
Set-Alias rmdir Remove-Item -Option AllScope -Scope Global
Set-Alias sleep Start-Sleep -Option AllScope -Scope Global
Set-Alias sort Sort-Object -Option AllScope -Scope Global
Set-Alias tee Tee-Object -Option AllScope -Scope Global
Set-Alias write Write-Output -Option AllScope -Scope Global
