#!/bin/bash

if [[ ! -f "private/config" ]]; then
   echo "Please provide private/config!";
   exit;
fi

./run-scripts stage
saveddir=$(pwd)
pushd /opt
"$saveddir/run-scripts" "$saveddir/languages"
popd
./run-scripts private
