#!/bin/bash

source private/setup.conf 
if [[ "$ConfigChanged" != "y" ]]; then
   echo "Please edit private/setup.conf!";
   exit;
fi
dnf update systemd -y
if [[ -z $(sestatus | grep "SELinux status:\s*enabled")  ]]; then
    ./run-scripts stage1 
    reboot
else
    ./setup-main
fi
