#!/bin/bash

LOGS=/var/log/tioupd
mkdir -p "$LOGS"

formattime() {
 if [ $1 -lt 60 ]; then
   echo "$1s"
 else
   echo "$((${1}/60))m $((${1}%60))s"
 fi
}

if [ $# -lt 1 ]; then
  echo "Usage: run-scripts <dir>"
  exit 1
fi

if [ ! -d $1 ]; then
  echo "Not a directory: $1"
  exit 1
fi

for i in $(LC_ALL=C; echo ${1%/}/*) ; do
  [ -d $i ] && continue

  if [ -x $i ]; then
    # run executable files
    logger -t "run-scripts[$$]" "($1) starting $(basename $i)"
    echo "$(date) Executing $(basename $i)..."
    start=`date +%s`
    echo "$(date)" >> "$LOGS/$(basename $i).log"
    $i >> "$LOGS/$(basename $i).log" 2>&1 
    status="$?"
    end=`date +%s`
    if [ "$status" -eq "0" ]; then
      status="SUCCESS"
    else
      status="FAILURE: $status"
    fi
    echo "$(date) Executed  $(basename $i)... $(formattime $((end-start))) {$status}"
    logger -t "run-scripts[$$]" "($1) finished $(basename $i) $(formattime $((end-start))) {$status}"
  fi
done

exit 0
