#!/bin/bash
for file in /usr/local/etc/runonce.d/*
do
    if [ ! -f "$file" ]
    then
        continue
    fi

    filebase=$(basename $file)
    stamp="$filebase.$(date +%Y%m%dT%H%M%S)"
    "$file" > "/var/log/runonce/$stamp.log" 2>&1
    mv "$file" "/usr/local/etc/runonce.d/ran/$filebase.$(date +%Y%m%dT%H%M%S)"
done
