#!/bin/bash

err=0
trap 'err=1' ERR

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/julia
rm -rf beeswax
git clone https://github.com/TryItOnline/beeswax.git
cd beeswax
HOME=/root ./build
cd ..

exit "$err"
