#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf emojicode
git clone https://github.com/emojicode/emojicode.git
cd emojicode
mkdir -p build
cd build
cmake -DheapSize=128000000 -DdefaultPackagesDirectory='"/opt/emojicode/packages"' .. -GNinja
ninja
ninja tests
cd Emojicode-*
ln -s $(pwd) ../../bin
ln -s $(pwd)/packages ../../packages
cd ../../..

exit "$err"
