#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf emojicode
git clone https://github.com/emojicode/emojicode.git
cd emojicode
git checkout 4cc4be517da29c6b7a47d790a93ef5f37a7807e7
make HEAP_SIZE=128000000 DEFAULT_PACKAGES_DIRECTORY=/opt/emojicode/packages
cd builds/*
ln -s $(pwd) ../../bin
ln -s $(pwd)/packages ../../packages
cd ../../..

#below uses the new build system once a later commit is pulled on TIO
#rm -rf emojicode
#git clone https://github.com/emojicode/emojicode.git
#cd emojicode
#mkdir -p build
#cd build
#cmake -DheapSize=128000000 -DdefaultPackagesDirectory= .. -GNinja
#ninja
#ninja tests
#cd Emojicode-*
#ln -s $(pwd) ../../bin
#ln -s $(pwd)/packages ../../packages
#cd ../../..

exit "$err"
