#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf Fireball
mkdir Fireball
curl --location --silent --output Fireball/Fireball.jar "$(
	curl --silent https://api.github.com/repos/okx-code/Fireball/releases \
		| jq --raw-output '.[0].assets[0].browser_download_url'
)"

exit "$err"
