#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf Fireball
mkdir Fireball
curl --location --silent --show-error --output Fireball/Fireball.jar "$(
    curl --silent --show-error https://api.github.com/repos/okx-code/Fireball/releases \
        | jq --raw-output 'sort_by(.published_at)|reverse|.[].assets|.[].browser_download_url' \
        | head -1 \
        | tee /dev/stderr
)"

exit "$err"
