#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf focal
wget ftp://www.cozx.com/pub/langs/focal-1.0.5.tar.gz
tar xf focal-1.0.5.tar.gz
rm -f focal-1.0.5.tar.gz
mv focal-1.0.5 focal
cd focal
make
cd ..

exit "$err"
