#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf Mathics
git clone https://github.com/mathics/Mathics.git
cd Mathics
python setup.py build
sed -i "1a\\\ndel __import__('sys').modules['os'].statvfs\\n" \
	build/lib/mathics/builtin/pympler/asizeof.py
python -mcompileall build

exit "$err"
