#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf assembly-fasm
mkdir assembly-fasm
curl --silent --show-error https://flatassembler.net/fasm-1.71.63.tgz \
	| tar xz --directory=assembly-fasm --strip-components=1

exit "$err"
