#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf assembly-fasm
mkdir assembly-fasm
cd assembly-fasm

curl --silent --show-error "https://flatassembler.net/$(
	curl --silent --show-error https://flatassembler.net/download.php \
		| grep -Pom 1 'fasm-[\d.]+tgz' \
		| tee /dev/stderr
)" \
	| tar xz --strip-components=1

exit "$err"
