#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf bc
mkdir bc
cd bc
curl --silent --show-error https://ftp.gnu.org/gnu/bc/bc-1.07.1.tar.gz \
	| tar xz --strip-components=1
CFLAGS=-O3 ./configure
make
make install

exit "$err"
