#!/bin/bash

set -o errexit -o pipefail

dir=/opt/chapel
rm -rf $dir
mkdir $dir
cd $dir
git clone --depth=1 https://github.com/chapel-lang/chapel.git build
cd build
export CHPL_TARGET_ARCH=native CHPL_COMM=gasnet CHPL_COMM_SUBSTRATE=smp CHPL_GASNET_MORE_CFG_OPTIONS="--disable-pshm-posix --enable-pshm-hugetlbfs"
./configure --prefix=/opt/chapel
make
export CHPL_COMM=none
./configure --prefix=/opt/chapel
make install
cd ..
rm -rf build
