#!/bin/bash

set -o errexit -o pipefail

dir=/opt/chapel
rm -rf $dir
mkdir -p $dir/build

curl --location --silent --show-error "$(
	curl --silent --show-error https://api.github.com/repos/chapel-lang/chapel/releases \
		| jq --raw-output 'max_by(.published_at).assets[0].browser_download_url' \
		| tee /dev/stderr
)" | tar xz --directory=$dir/build --strip-components=1

cd $dir/build
export CHPL_TARGET_ARCH=native CHPL_COMM=gasnet CHPL_COMM_SUBSTRATE=smp CHPL_GASNET_MORE_CFG_OPTIONS="--disable-pshm-posix --enable-pshm-hugetlbfs"
./configure --prefix=/opt/chapel
make
export CHPL_COMM=none
./configure --prefix=/opt/chapel
make install
cd ..
rm -rf build
