#!/bin/bash

err=0
trap 'err=1' ERR

export CLEAN_HOME=/opt/clean
PATH=$CLEAN_HOME/bin:$PATH

rm -rf clean
mkdir clean

curl --silent --show-error https://ftp.cs.ru.nl/Clean/builds/linux-x64/clean-bundle-complete-linux-x64-latest.tgz \
	| tar xz --directory=clean --strip-components=1

cd clean/lib
rm -r Generics
mv Platform/Deprecated/Generics .
shopt -s nullglob globstar
after=0
printf 'Compiling Clean modules'

while
	printf .
	before=$after
	after=($(
		for d in [[:upper:]]*; do
			cd $d

			for f in **/[[:alpha:]]*.dcl; do
				if [[ $f =~ ^Deprecated|^ESMVizTool ]]; then
					continue
				elif [[ $f =~ ^Data/Generics|^Internet/ ]]; then
					stdlib=Platform/Deprecated/StdLib
				else
					stdlib=StdLib
				fi
				f=${f%.*}
				f=${f//\//.}
				printf 'module main\nimport %s\nStart = ""\n' $f > main.icl
				clm -dynamics -IL Dynamics -IL Gast -IL GraphCopy -IL Generics -IL Platform -IL Sapl -IL TCPIP -IL ArgEnv -IL $stdlib -IL Directory main -o main.out
			done

			rm {.,Clean\ System\ Files}/main.*
			cd ..
		done 2> .stderr | sha512sum
	))
	[[ $before != $after ]]
do
	:
done

printf ' done.\nThe following errors occurred during the last pass:\n'
grep -Po 'Error((?!Error).)*' .stderr | cat -n
rm .stderr

exit "$err"
