#!/bin/bash

err=0
trap 'err=1' ERR

export CLEAN_HOME=/opt/clean

rm -rf clean
mkdir clean

curl --silent --show-error https://ftp.cs.ru.nl/Clean/builds/linux-x64/clean-bundle-complete-linux-x64-latest.tgz \
	| tar xz --directory=clean --strip-components=1

cd clean/lib
libs=$(printf -- '-IL %s ' [[:upper:]]*)
shopt -s nullglob

for d in [[:upper:]]*; do
	cd $d

	find -name '*.dcl' | sort | while read -N2; do
		read f
		f=${f%.*}
		f=${f//\//.}
		printf 'module main\nimport %s\nStart = ""\n' $f > main.icl
		printf '%s: %s\n' $d $f
		$CLEAN_HOME/bin/clm -dynamics $libs main -o main.out &> /dev/null
		$CLEAN_HOME/bin/clm -dynamics $libs main -o main.out &> /dev/null
		$CLEAN_HOME/bin/clm -dynamics $libs main -o main.out &> /dev/null
		$CLEAN_HOME/bin/clm -dynamics $libs main -o main.out &> /dev/null
		$CLEAN_HOME/bin/clm -dynamics $libs main -o main.out > /dev/null
		rm {.,Clean\ System\ Files}/main.*
	done

	cd ..
done

exit "$err"
