#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf cubically
git clone https://github.com/aaronryank/cubically.git
cd cubically
make

rm -rf /tmp/cubically-cache
./cubically fu examples/solve-1.cb <<< RLLUB
mv /tmp/cubically-cache cache
restorecon -R cache

exit "$err"
