#!/bin/bash

err=0
trap 'err=1' ERR

\rm -rf d
version=$(curl --show-error --silent downloads.dlang.org/releases/LATEST)
curl --location --show-error --silent \
	"downloads.dlang.org/releases/${version%%.*}.x/$version/dmd.$version.linux.tar.xz" \
	| tar x --transform='s:^[^/]*:d:' --xz
ln -fs "$PWD/d/linux/bin64/dmd" /usr/local/bin/

exit "$err"
