#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf dirty
git clone https://github.com/Ourous/dirty.git
cd dirty
cp -r /opt/clean .
mkdir clean/Temp
CLEAN_HOME=clean clean/bin/cpm dirty_linux.prj
rm -r clean

exit "$err"
