#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf elvm-ir
mkdir -p elvm-ir/bin
cd elvm-ir
git clone https://github.com/shinh/elvm.git build
cd build
bins=(out/{8cc,bfopt,elc,eli})
make \
	${bins[@]} \
	CFLAGS='-std=gnu99 $(COMMONFLAGS) -Wno-implicit-fallthrough' \
	CXXFLAGS='-std=c++11 $(COMMONFLAGS) -Wno-implicit-fallthrough'
mv ${bins[@]} ../bin/
mv libc ../include
cd ..
rm -r build

exit "$err"
