#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf emojicode
git clone https://github.com/emojicode/emojicode.git
cd emojicode
git checkout f74fc4a97778e6589b9bb6ae973769661bf0da81
make HEAP_SIZE=128000000 DEFAULT_PACKAGES_DIRECTORY=/opt/emojicode/packages
cd builds/Emojicode-*-x86_64-redhat-linux
ln -s $(pwd) ../../bin
ln -s $(pwd)/packages ../../packages
cd ../../..

#below uses the new build system once a later commit is pulled on TIO
#rm -rf emojicode
#git clone https://github.com/emojicode/emojicode.git
#cd emojicode
#mkdir -p build
#cd build
#cmake -DheapSize=128000000 -DdefaultPackagesDirectory= .. -GNinja
#ninja
#ninja tests
#cd Emojicode-*
#ln -s $(pwd) ../../bin
#ln -s $(pwd)/packages ../../packages
#cd ../../..

exit "$err"
