#!/bin/bash

rm -rf emojicode
git clone https://github.com/emojicode/emojicode.git
cd emojicode
make HEAP_SIZE=128000000 DEFAULT_PACKAGES_DIRECTORY=/opt/emojicode/packages
cd builds/*
ln -s $(pwd) ../../bin
ln -s $(pwd)/packages ../../packages
cd ../../..
