#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf emojicode6
mkdir emojicode6
cd emojicode6

curl -ssL "$(
	curl -sSL https://api.github.com/repos/emojicode/emojicode/releases \
		| jq --raw-output '
			.[0].assets[]|select(.name|test("-Linux-x86_64\\.tar\\.gz$")).browser_download_url
		'
)" | tar xz --strip-components=1

sed -i 's:/usr/local/EmojicodePackages:/opt/emojicode6/////packages:g' emojicodec
sed -i 's:/usr/local/include/emojicode:/opt/emojicode6//////include:g' emojicodec

exit "$err"
