#!/bin/bash

err=0
trap 'err=1' ERR

ln -sfT /usr/include/allegro5 /usr/include/allegro
rm -rf emojicode
mkdir -p emojicode/bin
cd emojicode
git clone https://github.com/emojicode/emojicode.git build
cd build
git checkout emojicode-0.5
mkdir build
cd build
cmake -DheapSize=128000000 -DdefaultPackagesDirectory=/opt/emojicode/packages .. -GNinja
ninja
ninja dist
cd Emojicode-*
mv emojicode* ../../../bin
mv packages ../../..
cd ../../..
rm -r build

exit "$err"
