#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf fantom
mkdir fantom
cd fantom
wget "$(
	curl --silent --show-error https://api.bitbucket.org/2.0/repositories/fantom/fan-1.0/downloads \
		| jq --raw-output '.values[0].links.self.href'
)"
unzip *.zip
rm *.zip
mv ./*/* .
rmdir fan*
bash adm/unixsetup

exit "$err"
