#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf felix
curl --location --silent --show-error https://github.com/TryItOnline/tiosetup-binaries/releases/download/felix/felix.tar.gz \
	| tar xz

export FLX_INSTALL_DIR=/opt/felix/lib/felix/felix-latest
cd felix
touch dummy.flx
bin/flx --cache-dir=/opt/felix/cache dummy.flx
rm -r ~/.felix dummy.flx cache/opt/felix/dummy.* flxg_stats.txt
mkdir cache/home
find cache -exec touch --date='+100 years' {} +
ln -s /home/runner cache/home/runner

exit "$err"
