#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf fish-shell/
rm -f /usr/local/bin/fish
git clone https://github.com/fish-shell/fish-shell.git
cd fish-shell
autoreconf --no-recursive
./configure
make
ln -fs "$PWD/fish" /usr/local/bin/
cd ..

exit "$err"
