#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf intercal
mkdir intercal
curl --silent --show-error http://www.catb.org/~esr/intercal/intercal-0.30.tar.gz \
	| tar xz --directory=intercal --strip-components=1
cd intercal
mkdir -p bin
cd bin
../configure
make
cd ../..

exit "$err"

