#!/bin/bash

rm -rf intercal-0.30
wget http://www.catb.org/~esr/intercal/intercal-0.30.tar.gz
tar zxvf intercal-0.30.tar.gz
rm -f intercal-0.30.tar.gz
cd intercal-0.30
mkdir -p bin
cd bin
../configure
make
cd ../..
