#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf j
mkdir j
curl --silent --show-error http://www.jsoftware.com/download/j805/install/j805_linux64.tar.gz \
	| tar xz --directory=j --strip-components=1
cd j

exit "$err"

