#!/bin/bash

err=0
trap 'err=1' ERR

dir=/opt/javascript-spidermonkey
rm -rf $dir
mkdir $dir
cd $dir

#curl --silent --show-error https://people-mozilla.org/~sfink/$(
#	curl --silent --show-error https://people-mozilla.org/~sfink/ \
#		| grep --only-matching --perl-regexp 'mozjs-[\d.]+\.tar\.bz2' \
#		| tail -1
#) | tar x --bzip2

megadl 'https://mega.nz/#!YDRWSbpZ!4_fbtDDLMfqGzewcP2qBpvxpqMFUeqnrmWBItMoY7wY'
tar xf mozjs-45.0.2.tar.bz2
\rm mozjs-45.0.2.tar.bz2

cd mozjs-*/js/src

cat > conf.diff <<.
*** configure   2017-07-20 22:38:47.976244887 +0000
--- configure  2017-07-20 22:38:02.914205160 +0000
***************
*** 15906,15912 ****
          fi
      fi

!     version=\`sed -n 's/^[:space:]*#[[:space:]]*define[[:space:]][[:space:]]*U_ICU_VERSION_MAJOR_NUM[[:space:]][[:space:]]*\([0-9][0-9]*\)[[:space:]]*$/\1/p' "\$icudir/common/unicode/uvernum.h"\`
      if test x"\$version" = x; then
         { echo "configure: error: cannot determine icu version number from uvernum.h header file \$lineno" 1>&2; echo "configure: error: cannot determine icu version number from uvernum.h header file \$lineno" 1>&5; exit 1; }
      fi
--- 15906,15912 ----
          fi
      fi

!     version=\`sed -n 's/^[[:space:]]*#[[:space:]]*define[[:space:]][[:space:]]*U_ICU_VERSION_MAJOR_NUM[[:space:]][[:space:]]*\([0-9][0-9]*\)[[:space:]]*$/\1/p' "\$icudir/common/unicode/uvernum.h"\`
      if test x"\$version" = x; then
         { echo "configure: error: cannot determine icu version number from uvernum.h header file \$lineno" 1>&2; echo "configure: error: cannot determine icu version number from uvernum.h header file \$lineno" 1>&5; exit 1; }
      fi
.
patch -i conf.diff configure
\rm conf.diff
cd $dir

mkdir build
cd build
../mozjs-*/js/src/configure --disable-shared-js --disable-tests --prefix=$dir
make
make install
cd ..
rm -rf build mozjs*
strip bin/js lib/*.ajs

exit "$err"
