#!/bin/bash

err=0
trap 'err=1' ERR

dir=/opt/javascript-spidermonkey
rm -rf $dir
mkdir $dir
cd $dir

#curl --silent --show-error https://people-mozilla.org/~sfink/$(
#	curl --silent --show-error https://people-mozilla.org/~sfink/ \
#		| grep --only-matching --perl-regexp 'mozjs-[\d.]+\.tar\.bz2' \
#		| tail -1
#) | tar x --bzip2

megadl 'https://mega.nz/#!YDRWSbpZ!4_fbtDDLMfqGzewcP2qBpvxpqMFUeqnrmWBItMoY7wY'
tar xf mozjs-45.0.2.tar.bz2
\rm mozjs-45.0.2.tar.bz2

mkdir build
cd build
../mozjs-*/js/src/configure --disable-shared-js --disable-tests --prefix=$dir
make
make install
cd ..
rm -rf build mozjs*
strip bin/js lib/*.ajs

exit "$err"
