#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf javascript-spidermonkey
curl --silent --show-error --location https://github.com/TryItOnline/tiosetup-binaries/releases/download/spidermonkey45/spidermonkey.tgz | tar x -z

exit "$err"
