#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf java-jdk
mkdir java-jdk
cd java-jdk

host=https://jdk.java.net
re_ver='(?<=<a href="/)\d+(?=/)'
ver="$(curl -sS $host | grep -Pom 1 "$re_ver")"
echo "Java JDK $ver"
re_url='https://download.java.net/[^"]+_linux-x64_bin\.tar\.gz'
url="$(curl -sS $host/$ver/ | grep -Pom 1 "$re_url")"
echo "$url"
curl -sSL "$url" | tar xz --strip-components=1

exit "$err"
