#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf julia6
mkdir julia6
cd julia6
curl --silent --show-error https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz \
	| tar xz --strip-components=1

export JULIA_PKGDIR=/opt/julia6/pkg

bin/julia --eval '
	Pkg.init()
	Pkg.add("Polynomials")
	using Polynomials
'

chmod -R +r pkg/lib
rm -r pkg/v0.6/METADATA

exit "$err"
