#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf julia
mkdir julia
curl --silent --show-error https://julialang.s3.amazonaws.com/bin/linux/x64/0.4/julia-0.4.7-linux-x86_64.tar.gz \
	| tar xz --directory=julia --strip-components=1

exit "$err"
