#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf julia5
mkdir julia5
curl --silent --show-error https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz \
	| tar xz --directory=julia5 --strip-components=1

exit "$err"
