#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf julia7
mkdir julia7
cd julia7
curl --silent --show-error https://julialang-s3.julialang.org/bin/linux/x64/0.7/julia-0.7.0-linux-x86_64.tar.gz \
	| tar xz --strip-components=1

JULIA_DEPOT_PATH=/opt/julia7/pkg bin/julia --eval '
	using Pkg
	Pkg.add("Polynomials")
	using Polynomials
'

rm -r pkg/registries
restorecon -R pkg
chmod -R +r pkg

exit "$err"
