#!/bin/bash

# This script requires read access to a private repo.

err=0
trap 'err=1' ERR

rm -rf k-ngn
mkdir k-ngn
cd k-ngn
git clone https://bitbucket.org/ngn/k.git build
cd build
make
cd ..
mv build/k .
rm -r build

exit "$err"
