#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf lean
mkdir lean
cd lean
curl -sSL https://leanprover.github.io/lean-nightly/build/lean-nightly-linux.tar.gz \
	| tar xz --strip-components=1
cd lib/lean
git clone https://github.com/leanprover/mathlib.git
cd mathlib

while
	curl -sSL "https://api.github.com/repos/leanprover/mathlib/commits/$(git rev-parse HEAD)/status" \
		| jq -e '.statuses[0].state!="success"'
do
	git checkout HEAD^
done

../../../bin/leanpkg build

exit "$err"
