#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf lean
mkdir lean
cd lean

curl -sSL "$(
	curl -sSL https://api.github.com/repos/leanprover/lean/releases \
		| jq -r '
			.[0].assets[]
			|select(.name|test("-linux\\.tar\\.gz$")).browser_download_url
		' \
		| tee /dev/stderr
)" \
	| tar xz --strip-components=1

cd lib/lean/library

curl -sSL "$(
	curl -sSL https://api.github.com/repos/leanprover-community/mathlib-nightly/releases \
		| jq -r '
			.[0].assets[]
			|select(.name|test("^mathlib-olean")).browser_download_url
		' \
		| tee /dev/stderr
)" \
	| tar xz --strip-components=1

exit "$err"
