#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf mariolang
git clone https://github.com/tomsmeding/MarioLANG.git mariolang
cd mariolang
clang mariolang.cpp -std=gnu++11 -lstdc++ -lm -o mariolang
cd ..

exit "$err"
