#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf mathics
mkdir mathics
cd mathics
HOME=. pipenv install mathics
find -name asizeof.py -exec sed -i "1a\\\ndel __import__('sys').modules['os'].statvfs\\n" {} \;

exit "$err"
