#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf mathics
git clone https://github.com/mathics/Mathics.git mathics
cd mathics
python setup.py build
cd build
ln -s lib* lib
sed -i "1a\\\ndel __import__('sys').modules['os'].statvfs\\n" \
	lib/mathics/builtin/pympler/asizeof.py
python -mcompileall lib

exit "$err"
