#!/bin/bash

err=0
trap 'err=1' ERR

version=nim-0.17.0

rm -rf nim
mkdir nim
cd nim

curl --location --silent --show-error https://nim-lang.org/download/$version.tar.xz \
	| tar x --xz

cd $version
./build.sh
./install.sh /opt
cd ..
rm -rf $version

exit "$err"
