#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf nim
mkdir nim
curl --silent --show-error https://nim-lang.org/download/nim-0.16.0.tar.xz \
	| tar xz --directory=nim --strip-components=1
chown -R root: nim/
cd nim
sh build.sh
cd ..

exit "$err"
