#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf osabie
git clone https://github.com/Adriandmen/05AB1E.git osabie
cd osabie
mix local.hex --force
mix local.rebar --force
mix deps.get --force
MIX_ENV=prod mix escript.build --force

exit "$err"
