#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf pari-gp
mkdir pari-gp
curl --silent --show-error http://pari.math.u-bordeaux.fr/pub/pari/unix/pari-2.9.1.tar.gz \
	| tar xz --directory=pari-gp --strip-components=1
cd pari-gp
./Configure
make gp
cd ..

exit "$err"
