#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf picolisp
mkdir picolisp
curl --silent --show-error http://software-lab.de/picoLisp.tgz \
	| tar xz --directory=picolisp --strip-components=1
cd picolisp/src64
make
cd ../..

exit "$err"
