#!/bin/bash

err=0
trap 'err=1' ERR

wget -O prolog-ciao.rpm http://ciao-lang.org/packages/1.14/13646/CiaoDE-1.14.2-13646.i386.rpm
rpm -i prolog-ciao.rpm
rm prolog-ciao.rpm
restorecon -Rv /usr/lib/ciao/ciao-*/

exit "$err"
