#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf pure
mkdir -p pure/build
cd pure/build

for ((page = 1; page <= 5; page++)); do
	url=$(
		curl -sSL https://api.github.com/repos/agraef/pure-lang/releases?page=$page \
			| jq -r '.[] | select(.name | test("^Pure [0-9.]+$")).assets[] | select(.name | test("pure-[0-9.]+\\.tar\\.gz$")).browser_download_url' \
			| head -1
	)
	[[ "$url" ]] && break
done

curl -sSL "$url" | tar xz --strip-components=1
curl -sSL https://github.com/TryItOnline/tiosetup-binaries/releases/download/llvm-3.5.2/llvm-3.5.2.tar.gz \
	| tar xz

llvm=/opt/pure/build/llvm-3.5.2
./configure --enable-release --prefix=/opt/pure CPPFLAGS=-I$llvm/include LDFLAGS=-L$llvm/lib -with-tool-prefix=$llvm/bin
make
make install
cd ..
rm -r build

exit "$err"
