#!/bin/bash

err=0
trap 'err=1' ERR

dir=/opt/python3-stackless
rm -rf $dir
mkdir -p $dir/build
cd $dir/build

printf -v ver '%.0sv%s-slp\n' $(python3 -V)
curl -sSL https://api.github.com/repos/stackless-dev/stackless/tarball/$ver \
	| tar xz --strip-components=1

./configure --prefix=$dir
make
make install
cd ..
rm -r build

exit "$err"
