#!/bin/bash

err=0
trap 'err=1' ERR

dir=/opt/python3-stackless
rm -rf $dir
mkdir $dir
cd $dir
git clone --depth=1 https://github.com/stackless-dev/stackless.git -b master-slp build
cd build
./configure --prefix=$dir
make
make install
cd ..
rm -r build

exit "$err"
