#!/bin/bash

err=0
trap 'err=1' ERR

dir=/opt/python3-stackless
rm -rf $dir
mkdir -p $dir/build
cd $dir/build
rtag="^v$(python3 -V | grep -Po '\d+\.\d+\.' | sed 's/\./\\\\./g')[0-9]+-slp"

curl -sSL "$(
	curl -sSL https://api.github.com/repos/stackless-dev/stackless/tags \
		| jq -r ".[] | select(.name | test(\"$rtag\")).tarball_url"
)" | tar xz --strip-components=1

./configure --prefix=$dir
make
make install
cd ..
rm -r build

exit "$err"
