#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf python2-iron
git clone --recursive https://github.com/IronLanguages/ironpython2.git python2-iron
cd python2-iron
sed -i '/IronPythonTest.csproj/,+1d' IronPython.sln
make
mv bin/Release/net45 ../python2-iron-bin
cd ..
rm -rf python2-iron
mv python2-iron-bin python2-iron
rm python2-iron/rowantest.*.dll

exit "$err"
