#!/bin/bash

err=0
trap 'err=1' ERR

home=/opt/microsoft/home
cd $home
rm -rf qsharp
HOME=$home dotnet new -i Microsoft.Quantum.ProjectTemplates::0.2.1806.1503-preview
HOME=$home dotnet new console -lang Q# -o qsharp
cd qsharp
HOME=$home dotnet restore

exit "$err"
