#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf r
curl https://cloud.r-project.org/src/base/R-latest.tar.gz | tar x --absolute-names --gzip --transform="s:^[^/]*:r/build:"
cd r
build/configure --with-x=no
make R

/opt/r/bin/Rscript -e 'install.packages(c("lpSolve", "Rmpfr", "Rsymphony", "gtools", "numbers", "pryr", "vegan"), repos = "http://cran.r-project.org")'
rm -rf build source src

exit "$err"
