#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf rail
wget http://www.xmission.com/~tyrecius/rail-0.5.tar.gz
tar xf rail-0.5.tar.gz
rm -f rail-0.5.tar.gz
mv rail-0.5 rail
chmod -R 755 rail
cd rail
./compile.sh
cd ..


exit "$err"
