#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf ring
mkdir ring
cd ring

wget "$(
    curl -sSL https://api.github.com/repos/ring-lang/ring/releases \
        | jq -r '.[0].assets[]|select(.name|test("Fedora")).browser_download_url'
)"

unzip *.zip ring/{bin,include,lib}'/*' -d ../
rm *.zip

exit "$err"
