#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf scheme-chez
mkdir scheme-chez
cd scheme-chez
git clone --depth=1 https://github.com/cisco/ChezScheme.git
cd ChezScheme
./configure --installprefix=/opt/scheme-chez
make
make install
cd ..
rm -rf ChezScheme

exit "$err"
