#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf snobol4
mkdir snobol4
curl --silent --show-error ftp://ftp.ultimate.com/snobol/snobol4-2.0.tar.gz \
	| tar xz --directory=snobol4 --strip-components=1
cd snobol4
make snobol4

exit "$err"
