#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf snuspi
wget https://raw.githubusercontent.com/graue/esofiles/master/snusp/impl/snuspi-0.1.zip
unzip -d snuspi -j snuspi-0.1.zip
rm snuspi-0.1.zip
cd snuspi
include=(/usr/lib/jvm/java-1.*.x86_64/include)
gcc -Wall -Wextra -shared -fPIC -I$include{,/linux} -z noexecstack -o libJNIPart.so JNIPart.c

exit "$err"
