#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf tampioi
git clone https://github.com/fergusq/tampio.git tampioi
cd tampioi
mkdir -p voikko
cd voikko
wget http://www.puimula.org/htp/testing/voikko-snapshot/dict-morpho.zip
unzip dict-morpho.zip
rm dict-morpho.zip

exit "$err"
