#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf taxi
git clone https://github.com/BigZaphod/Taxi.git taxi
cd taxi
g++ -std=c++03 -Wall -Wextra -Wpedantic source/taxi.cpp -o taxi -DNO_GREETINGS
cd ..

exit "$err"
