#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf unlambda
mkdir unlambda
curl --location --silent --show-error http://www.eleves.ens.fr:8080/home/madore/unlambda-2.0.0.tar.gz \
	| tar xz --directory=unlambda --strip-components=1
cd unlambda/c
gcc unlambda.c -o unlambda -lgc
cd ../..

exit "$err"

