#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf xeec
mkdir xeec
curl --silent --show-error http://paulo-jorente.de/poncho/esolang/xEec/interpreter/xEec.cpp \
	| g++ -x c++ -Wall -Wextra -O3 -o xeec/xEec -

exit "$err"
