#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf zig
mkdir zig
cd zig

curl -sSL "$(
	curl -sSL https://ziglang.org/download/index.json \
		| jq -r '.master|.["x86_64-linux"].tarball'
)" \
	| tar x --xz --strip-components=1

exit "$err"
