#!/bin/bash

if [[ ! -f "private/config" ]]; then
   echo "Please provide private/config!";
   exit;
fi
source private/config 

if [[ -z $(sestatus | grep "SELinux status:\s*enabled")  ]]; then
    ./run-scripts stage1 
    reboot
else
    rm -f stage1/410-installrunonce
    rm -f stage1/420-setcontinue
    ./run-scripts stage1 
    ./setup-main
fi
