#!/bin/bash

if [[ ! -f "private/config" ]]; then
   echo "Please provide private/config!";
   exit;
fi
source private/config 

# We run dnf update -y later, if we start logging to journald before that
# our logs can get screwed up because of different versiond of journald.
# Therefore, let's update systemd first, to avoid this problem altogether.
dnf update systemd -y

if [[ -z $(sestatus | grep "SELinux status:\s*enabled")  ]]; then
    ./run-scripts stage1 
    reboot
else
    rm -f stage1/410-installrunonce
    rm -f stage1/420-setcontinue
    ./run-scripts stage1 
    ./setup-main
fi
