#!/bin/bash

set +e

PREFIX=backend
DOMAIN=tryitonline.nz
ARENA=arena.tryitonline.nz

yes | cp files/backend.template "/etc/httpd/conf.d/meta.$DOMAIN.conf"
sed -i "s/DOMAIN/$DOMAIN/g" "/etc/httpd/conf.d/meta.$DOMAIN.conf"

wget https://raw.githubusercontent.com/TryItOnline/main-server/master/backend.tryitonline.net/run
sed -i "s/arena.tryitonline.net/$ARENA/g" run
mkdir -p "/srv/meta.$DOMAIN/"
mv -f run "/srv/meta.$DOMAIN/run-$PREFIX"
chmod +x "/srv/meta.$DOMAIN/run-$PREFIX"

sudo -u apache ssh-keyscan "$ARENA" >> $(getent passwd apache | cut -d: -f6)/.ssh/known_hosts
sudo -u apache ssh-keyscan $(dig +short "$ARENA") >> $(getent passwd apache | cut -d: -f6)/.ssh/known_hosts
