#!/bin/bash

err=0
trap "err=1" ERR

TRYITONLINENET=tryitonline.nz
TIORUN=tio.tryitonline.nz

BACKEND=backend.tryitonline.nz
SERVERCOSTS=this-is-a-site-copy
FEEDBACK=this-is-a-site-copy

git clone https://github.com/TryItOnline/main-server.git
yes | cp -r ./main-server/* /srv
rm -rf ./main-server
cd /srv
cd tryitonline.net
sed -i "s/tryitonline.net/$TRYITONLINENET/g" manifest.json
sed -i "s/tio.run/$TIORUN/g" manifest-nexus.json
sed -i "s/tryitonline.net/$TRYITONLINENET/g" index.html
sed -i "s/tio.run/$TIORUN/g" index.html
cd ..
cd tio.run
sed -i "s/backend.tryitonline.net/$BACKEND/g" index.html
sed -i "s/tio.run/$TIORUN/g" index.html
sed -i "s/server-costs@tryitonline.net/$SERVERCOSTS/g" index.html
sed -i "s/feedback@tryitonline.net/$FEEDBACK/g" index.html
sed -i "s/tryitonline.net/$TRYITONLINENET/g" index.html
sed -i "s/talk.$TRYITONLINENET/talk.tryitonline.net/g" index.html
sed -i "s/backend.tryitonline.net/BACKEND/g" nexus.html
sed -i "s/tio.run/$TIORUN/g" nexus.html
sed -i "s/server-costs@tryitonline.net/$SERVERCOSTS/g" nexus.html
sed -i "s/feedback@tryitonline.net/$FEEDBACK/g" nexus.html
sed -i "s/tryitonline.net/$TRYITONLINENET/g" nexus.html
sed -i "s/talk.$TRYITONLINENET/talk.tryitonline.net/g" nexus.html
cd ..
cd backend.tryitonline.net
sed -i "s/tryitonline.net/$TRYITONLINENET/g" run
sed -i "s/tryitonline.net/$TRYITONLINENET/g" run-legacy
cd ..

mkdir -p /srv/tmp
mkdir -p /srv/cache
mkdir -p /srv/store

exit "$err"
