#!/bin/bash

err=0
trap "err=1" ERR

source private/setup.conf 

yes | cp files/httpd/backend.tryitonline.net.conf /etc/httpd/conf.d/backend.tryitonline.net.conf
yes | cp files/httpd/nexus.tryitonline.net.conf /etc/httpd/conf.d/nexus.tryitonline.net.conf
yes | cp files/httpd/talk.tryitonline.net.conf /etc/httpd/conf.d/talk.tryitonline.net.conf
yes | cp files/httpd/tio.run.conf /etc/httpd/conf.d/tio.run.conf
yes | cp files/httpd/tryitonline.net.conf  /etc/httpd/conf.d/tryitonline.net.conf 

sed -i "s/ServerName tryitonline.net/ServerName $TRYITONLINENET/g" /etc/httpd/conf.d/tryitonline.net.conf 
sed -i "s/ServerName tio.run/ServerName $TIORUN/g" /etc/httpd/conf.d/tio.run.conf
sed -i "s/ServerName backend.tryitonline.net/ServerName $BACKEND/g" /etc/httpd/conf.d/backend.tryitonline.net.conf

sed -i 's/SSLEngine on/SSLEngine off/g' /etc/httpd/conf.d/ssl.conf
sed -i 's/#ServerName www.example.com:80/ServerName 127.0.0.1:80/g' /etc/httpd/conf/httpd.conf

chkconfig httpd on
systemctl restart httpd
   
exit "$err"
