#!/bin/bash

err=0
trap "err=1" ERR

source private/setup.conf 

certbot --staging --non-interactive --agree-tos --email $EMAIL --apache --domains $TRYITONLINENET,$TIORUN,$BACKEND --redirect

#TODO - copy existing certs


exit "$err"
