#!/bin/bash

err=0
trap "err=1" ERR

source private/setup.conf 

if [[ "$UseSavedCerts" != "y" ]]; then
    certbot --non-interactive --agree-tos --email $EMAIL --apache --domains $TRYITONLINENET,$TIORUN,$BACKEND --redirect
else
    certbot --staging --non-interactive --agree-tos --email $EMAIL --apache --domains $TRYITONLINENET,$TIORUN,$BACKEND --redirect
    tar xf private/letsencrypt.tar.gz -C /
    systemctl restart httpd
fi

exit "$err"
