#!/bin/bash

err=0
trap "err=1" ERR

#TODO - provide instructions for generation the key pair
mkdir -p $(getent passwd apache | cut -d: -f6)/.ssh
chown apache:apache $(getent passwd apache | cut -d: -f6)/.ssh
#sudo -u apache ssh-keygen -t rsa -f $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa -N ""
yes | cp private/id_rsa $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa
yes | cp private/id_rsa.pub $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa.pub

exit "$err"
