#!/bin/bash

err=0
trap "err=1" ERR

source private/setup.conf 

git clone https://github.com/TryItOnline/main-server.git
if [[ ! -z $MainServerCommit ]]; then
    cd main-server
    git checkout $MainServerCommit
    cd ..
fi
yes | cp -r ./main-server/* /srv
rm -rf ./main-server
cd /srv
cd tryitonline.net
sed -i "s/tryitonline.net/$TRYITONLINENET/g" manifest.json
sed -i "s/tio.run/$TIORUN/g" manifest-nexus.json
sed -i "s/tryitonline.net/$TRYITONLINENET/g" index.html
sed -i "s/tio.run/$TIORUN/g" index.html
cd ..
cd tio.run
sed -i "s/backend.tryitonline.net/$BACKEND/g" index.html
sed -i "s/tio.run/$TIORUN/g" index.html
sed -i "s://tryitonline.net://$TRYITONLINENET:g" index.html
sed -i "s/talk.$TRYITONLINENET/talk.tryitonline.net/g" index.html
sed -i "s/backend.tryitonline.net/$BACKEND/g" nexus.html
sed -i "s/tio.run/$TIORUN/g" nexus.html
sed -i "s://tryitonline.net://$TRYITONLINENET:g" nexus.html
sed -i "s/talk.$TRYITONLINENET/talk.tryitonline.net/g" nexus.html
cd ..
yes | cp etc/cache.default etc/cache
yes | cp etc/run.default etc/run
sed -i "s/\s*ssh_user_host=.*/ssh_user_host=runner@$ARENA/g" etc/run

mkdir -p /srv/tmp
chown apache:apache /srv/tmp
mkdir -p /srv/cache
chown apache:apache /srv/cache
mkdir -p /srv/store
chown apache:apache /srv/store

exit "$err"
