#!/bin/bash

err=0
trap "err=1" ERR

semanage fcontext -a -t httpd_sys_script_exec_t '/srv/backend.tryitonline.net(/.*)?'
semanage fcontext -a -t bin_t '/srv/bin(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/srv/cache(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/srv/store(/.*)?'
semanage fcontext -a -t httpd_sys_content_t '/srv/tio.run(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/srv/tmp(/.*)?'
semanage fcontext -a -t httpd_sys_content_t '/srv/tryitonline.net(/.*)?'
semanage fcontext -a -s system_u -t etc_t '/srv/etc(/.*)?'
semanage fcontext -a -s system_u -t lib_t '/srv/lib(/.*)?'
semanage fcontext -a -s system_u -t systemd_unit_file_t '/srv/lib/systemd(/.*)?'

restorecon -Rv /srv

exit "$err"
