#!/bin/bash

err=0
trap "err=1" ERR

source private/config

mkdir -p $(getent passwd apache | cut -d: -f6)/.ssh
chown apache:apache $(getent passwd apache | cut -d: -f6)/.ssh
#sudo -u apache ssh-keygen -t rsa -f $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa -N ""
yes | cp private/id_rsa $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa
yes | cp private/id_rsa.pub $(getent passwd apache | cut -d: -f6)/.ssh/id_rsa.pub
yes | cp files/ssh/config $(getent passwd apache | cut -d: -f6)/.ssh/config

sed -i "s/arena1.tryitonline.net/$ARENA/g" $(getent passwd apache | cut -d: -f6)/.ssh/config

exit "$err"
