#!/bin/bash

err=0
trap "err=1" ERR

source private/setup.conf 

sudo -u apache ssh-keyscan $ARENA > $(getent passwd apache | cut -d: -f6)/.ssh/known_hosts
sudo -u apache ssh-keyscan $(dig +short $ARENA) >> $(getent passwd apache | cut -d: -f6)/.ssh/known_hosts

exit "$err"
