#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf /srv
git clone https://github.com/TryItOnline/tryitonline.git /srv
source private/config

if [[ ! -z $TryItOnlineCommit ]]; then
    git -C /srv checkout $TryItOnlineCommit
fi

exit "$err"
