#!/bin/bash

err=0
trap "err=1" ERR

yes | cp files/renewal/renewssl.service /etc/systemd/system/renewssl.service
yes | cp files/renewal/renewssl.timer /etc/systemd/system/renewssl.timer

systemctl start renewssl.timer
systemctl enable renewssl.timer

exit "$err"
