#!/bin/bash

err=0
trap "err=1" ERR

cd /srv
yes | cp etc/trim-cache.default etc/trim-cache
systemctl link /srv/lib/systemd/tio-trim-cache.timer
systemctl link /srv/lib/systemd/tio-trim-cache.service
systemctl start tio-trim-cache.timer

exit "$err"
