#!/bin/bash

err=0
trap 'err=1' ERR

rm -f /etc/security/limits.d/99-tio.conf
cp files/system/ulimits.conf /etc/security/limits.d/99-tio.conf

rm -f /etc/sysctl.d/99-tio.conf
cp files/system/sysctl.d.conf /etc/sysctl.d/99-tio.conf

exit "$err"
