#!/bin/bash

err=0
trap "err=1" ERR

curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=835025
mkdir -p /opt/dotnet && tar zxf dotnet.tar.gz -C /opt/dotnet
ln -s /opt/dotnet/dotnet /usr/local/bin

exit "$err"
