#!/bin/bash

err=0
trap 'err=1' ERR

source private/config
if [[ "$OfflineMode" != "y" ]]; then
  dnf install psmisc selinux-policy-sandbox policycoreutils-sandbox selinux-policy-devel -y
fi

exit "$err"
