#!/bin/bash

err=0
trap 'err=1' ERR

source private/config

if [[ "$OfflineMode" != "y" ]]; then
  setsebool -P httpd_can_network_connect 1
  cp files/selinux/tryitonline.te .
  make -f /usr/share/selinux/devel/Makefile tryitonline.pp
  semodule -i tryitonline.pp
  rm -rf tryitonline.* tmp/
fi

exit "$err"
