#!/bin/bash

err=0
trap 'err=1' ERR

source private/config
if [[ "$OfflineMode" != "y" ]]; then
  cp files/selinux/tryitonline.te ./tryitonline.te
  make -f /usr/share/selinux/devel/Makefile tryitonline.pp
  semodule -i tryitonline.pp
  rm -f tryitonline.*
fi

exit "$err"
