#!/bin/bash

err=0
trap "err=1" ERR

source private/config
if [[ "$OfflineMode" != "y" ]]; then

  semanage fcontext -a -t bin_t '/opt(/.*)?/bin(/.*)?'
  semanage fcontext -a -t httpd_sys_rw_content_t '/srv/cache(/.*)?'
  semanage fcontext -a -t httpd_sys_content_t '/srv/var/www(/.*)?'
  semanage fcontext -a -t httpd_sys_script_exec_t '/srv/var/www/.*/cgi-bin(/.*)?'
  semanage fcontext -a -t httpd_sys_rw_content_t '/srv/tmp(/.*)?'
  semanage fcontext -a -t bin_t '/srv/bin(/.*)?'
  semanage fcontext -a -t etc_t '/srv/etc(/.*)?'
  semanage fcontext -a -t lib_t '/srv/lib(/.*)?'
  semanage fcontext -a -t systemd_unit_file_t '/srv/lib/systemd(/.*)?'
  semanage fcontext -a -t bin_t '/srv/sbin(/.*)?'
  semanage fcontext -a -t bin_t '/srv/wrappers(/.*)?'

  restorecon -Rv /srv

  semanage fcontext -a -t bin_t '/usr/lib/(.*/)?bin(/.*)?'
  semanage fcontext -a -t bin_t '/usr/lib/mlton/(mlton-compile|platform|static-library)'
  semanage fcontext -a -t bin_t '/usr/lib/node_modules/cheddar-lang/dist/cli(/.*)?'
  semanage fcontext -a -t bin_t '/usr/lib/clisp-.*/base(/.*)?'
  semanage fcontext -a -t bin_t '/usr/lib/maxima/.*/binary-sbcl(/.*)?'
  semanage fcontext -a -t bin_t '/usr/lib/golang/pkg/tool/linux_amd64(/.*)?'
  semanage fcontext -a -t bin_t '/usr/local/haskell/.*/bin(/.*)?'
  semanage fcontext -a -t bin_t '/usr/lib/fpc/.*/ppc.*'
fi

exit "$err"
