#!/bin/bash

err=0
trap 'err=1' ERR

dnf install wget -y
rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
dnf config-manager --add-repo http://download.mono-project.com/repo/centos/
dnf copr enable dmoerner/outils -y
dnf copr enable petersen/idris -y
dnf copr enable tcg/devel -y
sed -i 's/$releasever/26/g' /etc/yum.repos.d/*copr*dmoerner*outils*.repo
wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-ceylon https://downloads.ceylon-lang.org/rpm/ceylon-rpm-repo.gpg.key
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-ceylon
dnf config-manager --add-repo https://downloads.ceylon-lang.org/rpm/ceylon.repo
rpm --import https://dist.crystal-lang.org/rpm/RPM-GPG-KEY
echo -e '[crystal]\nname=Crystal\nbaseurl=https://dist.crystal-lang.org/rpm/\nenabled=1' > /etc/yum.repos.d/crystal.repo
echo -e '[codestation]\nname=Codestation packages for Fedora 26 - $basearch\nbaseurl=https://codestation.org/fedora/\nenabled=1\ngpgcheck=0\npriority=100' > /etc/yum.repos.d/codestation.repo
wget -O /etc/yum.repos.d/bintray-pony-language-ponyc-rpm.repo https://bintray.com/pony-language/ponyc-rpm/rpm
echo 'deltarpm=no' >> /etc/dnf/dnf.conf
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'

exit "$err"
