#!/bin/bash

err=0
trap 'err=1' ERR

dnf install allegro5-devel allegro5-addon-acodec-devel allegro5-addon-image-devel allegro5-addon-ttf-devel ant bind-utils bison bison-devel boo bsd-games bzip2-devel ceylon-1.3.2 chrpath \
  clang clisp clojure cmake cpio crystal dash elixir emacs-nox erlang erlang-erts file flex flex-devel fpc freetype-devel fsharp gambit-c gcc-c++ \
  gc-devel gettext-devel gforth git glib2-devel glibc-devel gmp-c++ gmp-devel golang gradle \
  groovy gsl-devel gtkglext-libs httpd huginn icu ImageMagick java-1.?.0-openjdk jq \
  ksh libICE-devel libSM-devel libX11-devel libXaw-devel libXext-devel libXft-devel libXinerama-devel \
  libXmu-devel libXpm-devel libXrender-devel libXt-devel libarchive-devel libcurl-devel libdb-devel libedit-devel libmpc-devel \
  libgcc.i686 libicu libjpeg-turbo-devel libunwind lldb lldb-devel llvm lttng-tools lttng-ust \
  maxima mercurial mlton mod_ssl mono-basic mono-complete mpfr-devel nano nasm ncurses-compat-libs neovim npm \
  ocaml octave octave-devel openssl-devel outils patch pcre-devel perl-Digest-CRC perl-List-MoreUtils \
  perl-Text-Soundex php-cli ponyc psmisc pyephem pypy python3-devel python-certbot-apache python-devel rakudo \
  redhat-rpm-config ruby rust scala sqlite squirrel sudo tcl-trf tcsh time tree unixODBC-devel uuid-devel vala vim-common \
  words xz xz-devel zsh 'apache-commons-*' -y

# For blc
dnf install glibc-devel.i686 -y

if [[ "$(uname -a)" =~ \.fc25\. ]]; then
  dnf install java-9-openjdk-devel -y
else
  sed -i 's/$releasever/25/g' /etc/yum.repos.d/_copr_omajid-openjdk9.repo
  dnf install java-9-openjdk-devel -y
fi

exit "$err"
