#!/bin/bash

err=0
trap 'err=1' ERR

dnf install allegro5-devel ant bind-utils bison bison-devel bsd-games bzip2-devel ceylon-1.3.2 chicken chrpath \
  clang clisp clojure cmake cpio crystal dash emacs-nox erlang-erts file fish flex flex-devel freetype-devel fsharp gcc-c++ \
  gc-devel gforth git glib2-devel glibc-devel glibc-devel.i686 gmp-c++ gmp-devel golang gradle \
  groovy gtkglext-libs httpd icu ImageMagick java-1.?.0-openjdk java-9-openjdk-devel jq \
  ksh libICE-devel libSM-devel libX11-devel libXaw-devel libXext-devel libXft-devel libXinerama-devel \
  libXmu-devel libXpm-devel libXrender-devel libXt-devel libarchive-devel libcurl-devel libedit-devel \
  libgcc.i686 libicu libjpeg-turbo-devel libunwind lldb lldb-devel llvm lttng-tools lttng-ust \
  maxima mercurial mlton mod_ssl mono-basic mono-complete-4.8.1.0 nano nasm ncurses-compat-libs neovim npm \
  ocaml octave octave-devel openssl-devel outils patch pcre-devel perl-Digest-CRC perl-List-MoreUtils \
  perl-Text-Soundex php-cli psmisc pyephem pypy python3-devel python-certbot-apache python-devel rakudo \
  redhat-rpm-config ruby rust scala sudo tcl-trf tcsh time tree unixODBC-devel uuid-devel vala vim-common \
  words xz xz-devel zsh 'apache-commons-*' -y

dnf config-manager --set-disabled download.mono-project.com_repo_centos_

exit "$err"
