#!/bin/bash

err=0
trap 'err=1' ERR

source private/config

cd /srv
[[ "$OfflineMode" == "y" ]] && protocol=http || protocol=https

sed --in-place "
	s#https://tryitonline\.net#$protocol://$TRYITONLINENET#g
	s#https://tio\.run#$protocol://$TIORUN#g
" */*.html */manifest*.json

for f in etc/*.default
do
	cp $f ${f%.default}
done

arenactl add runner@127.0.0.1
arenactl enable runner@127.0.0.1

mkdir -p /srv/tmp
chown apache:apache /srv/tmp
mkdir -p /srv/cache/{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}
chown -R apache:apache /srv/cache
mkdir -p /srv/store
chown apache:apache /srv/store
if [[ "$OfflineMode" != "y" ]]; then
  restorecon -Rv /srv
else
  sed -i 's/^\(no_selinux=\).*/\1true/' etc/run
fi

exit "$err"
