#!/bin/bash

err=0
trap 'err=1' ERR

source private/config

cd /srv

for f in etc/*.default; do
    cp $f ${f%.default}
done

tiobuild $TIORUN

tiopool add "$HOSTNAME"
tiopool enable "$HOSTNAME"

mkdir -p /srv/tmp
chown apache:apache /srv/tmp
mkdir -p /srv/cache/{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}{0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f}
chown -R apache:apache /srv/cache

if [[ "$OfflineMode" != "y" ]]; then
  restorecon -Rv /srv
fi

exit "$err"
