#!/bin/bash

err=0
trap 'err=1' ERR

curl \
	--location \
	--silent \
	--show-error \
	--output /usr/local/lib/libstdbuf.so \
	--url https://github.com/TryItOnline/tiosetup-binaries/releases/download/libstdbuf-x86/libstdbuf.so

ln -fst /usr/local/lib64 /usr/libexec/coreutils/libstdbuf.so

g++ -fPIC files/system/tiopreload.cpp -shared -o /usr/local/lib64/tiopreload.so
g++ -fPIC files/system/tiopreload.cpp -shared -m32 -o /usr/local/lib/tiopreload.so

exit "$err"
