#!/bin/bash

err=0
trap "err=1" ERR

source private/config
[[ $LANGDOMAIN ]] || LANGDOMAIN=example.net LD=#

for file in /etc/httpd/conf.d/*.conf; do
	> "$file"
done

cat > /etc/httpd/conf.d/000-global.conf <<.
ServerName $TRYITONLINENET
Listen 443 https
SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300
SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin
SSLCryptoDevice builtin
.

cat > /etc/httpd/conf.d/010-tryitonline.conf << .
<VirtualHost *:80>
	RewriteEngine On
	ServerName $TRYITONLINENET
	DocumentRoot /srv/tryitonline.net
	Header always set Access-Control-Allow-Origin "*"
	AddOutputFilterByType DEFLATE text/html
	AddOutputFilterByType DEFLATE application/javascript
	AddOutputFilterByType DEFLATE application/json
	AddOutputFilterByType DEFLATE application/octet-stream
	AddType application/font-woff2 .woff2
	ExpiresActive On
	ExpiresByType application/font-woff "access plus 1 year"
	ExpiresByType application/font-woff2 "access plus 1 year"

	<Directory /srv/tryitonline.net>
		Options Indexes FollowSymLinks
		AllowOverride None
		Require all granted
	</Directory>
</VirtualHost>
.

cat > /etc/httpd/conf.d/020-tio.run.conf << .
<VirtualHost *:80>
	RewriteEngine On
	ServerName $TIORUN
$LD	ServerAlias *.$LANGDOMAIN
	DocumentRoot /srv/tio.run
	AddOutputFilterByType DEFLATE text/html
	AddOutputFilterByType DEFLATE application/javascript
	AddOutputFilterByType DEFLATE application/octet-stream
$LD	RewriteCond %{HTTP_HOST} ^([^.]*)\\.${LANGDOMAIN//./\\.}\$
$LD	RewriteRule "" https://$TIORUN/nexus/%1 [R=301]
	RewriteRule "^/nexus(-[^/]+)?(/|$)" "/nexus\$1.html"

	<Directory /srv/tio.run>
		Options Indexes FollowSymLinks
		AllowOverride none
		Require all granted
	</Directory>

	ScriptAlias /cgi-bin /srv/tio.run/cgi-bin/
	TimeOut 70

	<Directory /srv/tio.run/cgi-bin>
		Header always set Access-Control-Allow-Origin "*"
		AllowOverride none
		Options +ExecCGI -MultiViews
		Require all granted
	</Directory>
</VirtualHost>
.

echo 'http_server=httpd' > /srv/etc/tio-web
if [[ "$OfflineMode" != "y" ]]; then
  systemctl enable tio-web
  systemctl start tio-web
fi
exit "$err"
