#!/bin/bash

err=0
trap "err=1" ERR

source private/config
[[ $LANGDOMAIN ]] || LANGDOMAIN=example.net LD=#

for file in /etc/httpd/conf.d/*.conf; do
	> "$file"
done

cat > /etc/httpd/conf.d/000-global.conf <<.
ServerName $TRYITONLINENET
Listen 443 https
SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
SSLSessionCache shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout 300
SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin
SSLCryptoDevice builtin
.

cat > /etc/httpd/conf.d/010-tio.run.conf << .
RewriteEngine On

<VirtualHost *:80>
	ServerName $TIORUN

	RewriteRule ^/(.*)$ https://$TIORUN/$1 [R=301]
</VirtualHost>

<VirtualHost *:443>
	ServerName $TIORUN

	AddOutputFilterByType DEFLATE application/javascript
	AddOutputFilterByType DEFLATE application/json
	AddOutputFilterByType DEFLATE image/vnd.microsoft.icon
	AddOutputFilterByType DEFLATE text/css
	AddOutputFilterByType DEFLATE text/html
	DocumentRoot /srv/var/www/$TIORUN
	Header always set Access-Control-Allow-Origin "*"
	RewriteRule ^/nexus /index.html
	ScriptAlias /cgi-bin /srv/var/www/$TIORUN/cgi-bin/
	SSLCertificateFile /etc/letsencrypt/live/$TIORUN/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/$TIORUN/privkey.pem
	TimeOut 70

	<Directory /srv/var/www/$TIORUN>
		AllowOverride None
		Options SymLinksIfOwnerMatch
		Require all granted
	</Directory>

	<Files index.html>
		Header set Cache-Control "max-age=60; must-revalidate"
	</Files>

	<Directory ~ /srv/var/www/$TIORUN/static>
		Header set Cache-Control max-age=1000000000
	</Directory>

	<Directory /srv/var/www/$TIORUN/cgi-bin>
		Options ExecCGI
	</Directory>

</VirtualHost>

<VirtualHost *:80>
	ServerName $TRYITONLINENET
$LD	ServerAlias *.$LANGDOMAIN

	Header always set Access-Control-Allow-Origin "*"

	RewriteCond %{HTTP_HOST} ^(www\.)?${TRYITONLINENET//./\.}$
	RewriteRule ^/(.*)$ https:// $TIORUN/$1 [R=301]

$LD	RewriteCond %{HTTP_HOST} ^([^.]*)\.$TRYITONLINENET$
$LD	RewriteRule ^/$ https://$TIORUN/nexus/%1 [R=301]
</VirtualHost>

<VirtualHost *:443>
	ServerName $TRYITONLINENET

	Header always set Access-Control-Allow-Origin "*"
	Header always set Cache-Control max-age=2400000
	SSLCertificateFile /etc/letsencrypt/live/$TIORUN/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/$TIORUN/privkey.pem

	RewriteRule ^/$ https://$TIORUN/#home [NE,R=301]
	RewriteRule ^/(.+)$ https://$TIORUN/$1 [R=301]
</VirtualHost>
.

echo 'http_server=httpd' > /srv/etc/tio-web
if [[ "$OfflineMode" != "y" ]]; then
	systemctl enable tio-web
fi
exit "$err"
