#!/bin/bash

err=0
trap "err=1" ERR

search_certs()
{
	[[ -e "$1/id_rsa" && -e "$1/id_rsa.pub" ]] || [[ -e "$1/id_ed25519" && -e "$1/id_ed25519.pub" ]]
}

source private/config

mkdir -p ~apache/.ssh

for user in apache root; do
	ssh=$(eval echo ~$user)/.ssh
	cp files/ssh/config "$ssh"
	if search_certs "$ssh"; then
		continue
	elif search_certs private/$user; then
		cp private/$user/id_* "$ssh"
		chmod 600 "$ssh"/!(*.pub)
	else
		ssh-keygen -C $user@$TRYITONLINENET -f "$ssh/id_ed25519" -N '' -t ed25519
	fi
done

chown -R apache: ~apache
cat ~root/.ssh/*.pub >> ~root/.ssh/authorized_keys

cd private
if [[ -e ssh_host_rsa_key && -e ssh_host_rsa_key.pub ]] || [[ -e ssh_host_ed25519_key && -e ssh_host_ed25519_key.pub ]]; then
	sed 's/^/* /' ssh_host_*_key.pub >> /etc/ssh/ssh_known_hosts
	cp ssh_host_*_key* /etc/ssh/
        chmod 640 /etc/ssh/ssh_host_*_key
        chmod 644 /etc/ssh/ssh_host_*_key.pub
		chown root:ssh_keys /etc/ssh/ssh_host_*_key
else
	sed 's/^/* /' /etc/ssh/ssh_host_ed25519_key.pub >> /etc/ssh/ssh_known_hosts
fi
cd ..

exit "$err"
