#!/bin/bash

err=0
trap "err=1" ERR

source private/config

if [[ "$OfflineMode" != "y" ]]; then
	TIO_PORT=443
	TIO_PROTOCOL=https
else
	TIO_PORT=80
	TIO_PROTOCOL=http
	rm files/httpd/*-ssl.conf
fi

if [[ "$TALKDOMAIN" && "$TALKURL" ]]; then
	TALK_REGEX=${TALKDOMAIN//./\\.}
else
	TALK_IF=#
fi

if [[ "$LANGDOMAIN" ]]; then
	LANG_REGEX=${LANGDOMAIN//./\\.}
else
	LANG_IF=#
fi

export \
	TRYITONLINENET TIORUN TIO_PORT TIO_PROTOCOL \
	TALKDOMAIN TALK_IF TALK_REGEX TALKURL \
	LANGDOMAIN LANG_IF LANG_REGEX HSTS_DIRECTIVES

for file in /etc/httpd/conf.d/*.conf; do
	> "$file"
done

cd files/httpd

for file in *.conf; do
	envsubst < $file > /etc/httpd/conf.d/$file
done

echo -e 'http_server=httpd\nmkdir -p /var/log/httpd' > /srv/etc/tio-web

if [[ "$OfflineMode" != "y" ]]; then
	systemctl enable tio-web
	systemctl restart tio-web
fi

exit "$err"
