#!/bin/bash

err=0
trap 'err=1' ERR

cpanm -M https://cpan.metacpan.org \
	Acme::Chef Array::Utils Data::Dumper::Compact Inline Inline::C Inline::Python IPC::Run3 Keyword::Declare Language::Farnsworth Lingua::EN::Inflect Math::Prime::Util::GMP Modern::Perl Quote::Code Perl6::Slurp Perl6::Take Statistics::Basic Zoidberg

exit "$err"
