#!/bin/bash

err=0
trap 'err=1' ERR

npm install -g cheddar-lang coffee-script babel-cli mathjs escape-string-regexp clear readline-sync decimal.js minimist shunt.js bignumber.js opn request typescript readwrite colors commander pkginfo

exit "$err"
