#!/bin/bash

err=0
trap 'err=1' ERR

octave --eval "
	pkg install -auto -forge image;
	pkg install -auto -forge io;
	pkg install -auto -forge statistics;
	pkg install -auto -forge symbolic;
"

exit "$err"
