#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf /opt/lua
mkdir -p /opt/lua/share
cd /opt/lua
git clone --depth 1 https://github.com/TehFlaminTaco/equa.lua.git
mv equa.lua/equa.lua share/
rm -r equa.lua

exit "$err"
