#!/bin/bash

err=0
trap 'err=1' ERR

cabal update
cabal install --global HaskellForMaths data-ordlist dates digits heredoc monadlist numbertheory microlens-mtl microlens-th polynomial regex-compat statistics

exit "$err"
