#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf /opt/julia6/pkg
export JULIA_PKGDIR=/opt/julia6/pkg

/opt/julia6/bin/julia --eval '
	Pkg.init()
	Pkg.add("Polynomials")
	using Polynomials
'

chmod -R +r /opt/julia6/pkg/lib
rm -r /opt/julia6/pkg/v0.6/METADATA

exit "$err"
