#!/bin/bash

err=0
trap 'err=1' ERR

source private/config

mkdir -p /opt/microsoft/libs
wget https://github.com/TryItOnline/DynamicExpresso/releases/download/tio-1/DynamicExpresso.zip
unzip -d /opt/microsoft/libs/DynamicExpresso DynamicExpresso.zip
rm -f DynamicExpresso.zip

netcoredeps

if [[ "$OfflineMode" == "y" ]]; then
  ln -fs /opt/microsoft/home/.nuget /home/runner/
fi


find /opt/microsoft/home -type d -exec chmod 755 {} \;
find /opt/microsoft/home -exec chmod o-w {} \;

exit "$err"
