#!/bin/bash

err=0
trap 'err=1' ERR

source private/config
saveddir=$(pwd)

mkdir -p /opt/microsoft/home/csharp
pushd /opt/microsoft/home/csharp
cp "$saveddir/files/dotnet/project.csproj" ./project.csproj
mkdir -p /opt/microsoft/tmp
HOME=/opt/microsoft/home TMPDIR=/opt/microsoft/tmp dotnet restore
if [[ "$OfflineMode" == "y" ]]; then
  ln -fs /opt/microsoft/home/.nuget /home/runner/
fi
rm -rf /opt/microsoft/tmp
popd

find /opt/microsoft/home -type d -exec chmod 755 {} \;
find /opt/microsoft/home -exec chmod o-w {} \;

exit "$err"
