#!/bin/bash

err=0
trap 'err=1' ERR

mkdir -p tmp
cd tmp
dnf install -y https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.1/powershell-6.0.0_beta.1-1.el7.centos.x86_64.rpm
wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
mono nuget.exe install runtime.fedora.24-x64.Microsoft.NETCore.Runtime.CoreCLR -Pre
mv runtime.fedora.24-x64.Microsoft.NETCore.Runtime.CoreCLR.* /opt/microsoft/coreclr
pushd /opt/microsoft
chmod +x coreclr/tools/crossgen
tmperr=$err
for f in powershell/6.0.0-beta.1/*.dll; do coreclr/tools/crossgen -JITPath dotnet/shared/Microsoft.NETCore.App/*/libclrjit.so -Platform_Assemblies_Paths coreclr/runtimes/fedora.24-x64/native:powershell/6.0.0-beta.1 "$f"; done
err=$tmperr
popd
cd ..
rm -rf tmp ~/.nuget/ ~/.config/NuGet/ ~/.local/share/NuGet/
cp files/powershell/aliases.ps1 /opt/microsoft/lib64/

exit "$err"
