#!/bin/bash

err=0
trap 'err=1' ERR

cd /opt
rm -rf prolog-swi
mkdir -p prolog-swi/build
cd prolog-swi/build
chown keeper: .
sudo -u keeper bash -c '
	git clone --depth=1 --recursive https://github.com/SWI-Prolog/swipl-devel.git .
	#hotfix
	mkdir -p packages/http/figs
	touch packages/http/figs/httpserver.{pdf,png}
	mkdir build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX=/opt/prolog-swi ..
	make
'
cd build
make install
cd ../..
ln -sf /opt/prolog-swi/bin/swipl /usr/local/bin
rm -r build

exit "$err"
