#!/bin/bash

err=0
trap 'err=1' ERR

dnf install psmisc selinux-policy-sandbox policycoreutils-sandbox setroubleshoot selinux-policy-devel -y
sed -i 's/SELINUX=disabled/SELINUX=enforcing/g' /etc/selinux/config
cp files/selinux/arena.te ./arena.te
make -f /usr/share/selinux/devel/Makefile arena.pp
semodule -i arena.pp
rm arena.*

#exit "$err"
exit 1
